### ISSUE TITLE
Combind Chart [BUGS]

### ISSUE THREAD

**Issue by m2faridi** [SunPointed/MPFlutterChart#117]
some time start chart have this errore

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following UnsupportedError was thrown during paint():
Unsupported operation: Result of truncating division is Infinity or NaN

The relevant error-causing widget was: 
  CombinedChart file:///Users/m2faridi/mychart/lib/activity_chart.dart:793:19
When the exception was thrown, this was the stack: 
#0      double._trunc_div (dart:core-patch/double.dart:47:57)
#1      double.~/ (dart:core-patch/double.dart:43:12)
#2      AxisRenderer.computeAxisValues (package:mp_chart/mp/core/render/axis_renderer.dart:160:62)
#3      XAxisRenderer.computeAxisValues (package:mp_chart/mp/core/render/x_axis_renderer.dart:64:11)
#4      XAxisRenderer.computeAxis (package:mp_chart/mp/core/render/x_axis_renderer.dart:59:5)

**Comment by m2faridi** [comment]
This chart is no longer supported?
